version: "3"
services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - app-data:/var/www/application:cached
      - ~/.aws:/root/.aws
      - ~/.aws:/home/www-data/.aws
    networks:
      - container_network
    depends_on:
      - "db"

  web:
    env_file: .env
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    ports:
      - "8080:80"
    networks:
      - container_network
    volumes:
      - app-data:/var/www/application:cached
    depends_on:
      - "app"

  node:
    image: node:12.16.2-alpine
    # networks:
    #   container_network:
    #     ipv4_address: "192.168.240.5"
    ports:
      - "3000:3000"
    volumes:
      - app-data:/var/www/application:cached
    command: /bin/sh -c "cd /var/www/application && npm install && npm run dev"
    depends_on:
      - "web"

  db:
    ports:
      - "3306:3306"
    build:
      context: .
      dockerfile: ./dockerfiles/db/Dockerfile
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - container_network
    volumes:
      - ./db_data:/var/lib/mysql
  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    networks:
      - container_network

###### 開発用ネットワーク・ボリューム ########
networks:
  container_network:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 192.168.240.0/24
volumes:
  app-data:
    driver_opts:
      type: none
      device: $PWD
      o: bind